### ISSUE TITLE
After successful verification, the idle file did not delete the temporary file for some reason.

### ISSUE THREAD

**Issue by httpservlet** [CESSProject/cess-miner#302]
The total size of the idle file after successful verification should be 16G, but in my miner, it is 32G. For some reason, 16G of temporary files were not deleted, which will affect the subsequent P disk space.

**Comment by jiuquxzy** [comment]
This issue has been fixed in the new version：
https://github.com/CESSProject/cess_pois/tree/v0.5.17
Will be pushed in the next version of cess-miner

**Comment by AstaFrode** [comment]
Fixed on b929463fc805a92df0b6e6e4db189c693c6d1ea6
