### ISSUE TITLE
Miners choose TEEworker independently

### ISSUE THREAD

**Issue by democ98** [CESSProject/cess-miner#303]
* Background: Due to the chain’s challenge mechanism, miners are forced to use public free TEEworkers to work,which is pretty slow.
* Problem: Miners sometimes have difficulty connecting to TEE Workers, resulting in unnecessary penalties.
* Solution: When a miner starts, it can specify a TEE worker list. A miner that specifies a TEE worker list will only interact with the TEE workers in the list. If a miner does not specify a TEE worker, it will be randomly selected from the TEE worker list on the chain.

**Comment by democ98** [comment]
Pls assign this issue to 
democ98,[0xbillw](https://github.com/0xbillw), [ytqaljn](https://github.com/ytqaljn),[jiuquxzy](https://github.com/jiuquxzy).and set Lable to 'Feature Add'.
And check this CESS repository issue also,it is same one:https://github.com/CESSProject/cess/issues/414#issue-2670634409

**Comment by AstaFrode** [comment]
Completed on [p2p_to_http](https://github.com/CESSProject/cess-miner/tree/p2p_to_http)
